some cleanup, docs, plug added cloudify's cli as a node in the blueprint

diff --git a/simple/components/utils b/simple/components/utils
--- a/simple/components/utils
+++ b/simple/components/utils
@@ -3,7 +3,6 @@
 function sys_error
 {
     ctx logger error "${1:-UNKNOWN} (status $?)"
-    # ctx logger error "${1:-UNKNOWN} (status $?)"
     exit 1
 }
 
@@ -48,15 +47,13 @@ function install_module
 }
 
 
+# DEPRECATED
 function install_rpm
 {
     source=$1
     if [[ -z "${source}" ]]; then
         sys_error "Must supply url as param (install_rpm #URL#)."
     fi
-
-    # ctx logger info "Installing RPM ${tmp_file_path}..."
-    # sudo yum install -y ${source}
 
     tmp_file_path="/tmp/${RANDOM}.rpm"
     download_file ${source} ${tmp_file_path}
@@ -71,44 +68,73 @@ function clean_tmp
     sudo rm -rf /tmp/*
 }
 
+function curl_download_with_retries
+{
+    ###
+    # This will download a file.
+    # It will retry 10 times; provide an error if failure occurs rather than an html page;
+    # no output will be shows other than errors, and any directory structure required
+    # for the download will be created automatically.
+    ###
+    source=$1
+    destination=$2
+
+    # this will use an exponential backoff algorithm 10 times before it fails.
+    curl --retry 10 --fail --silent --show-error --location ${source} --create-dirs --output ${destination}
+}
+
+function wget_download_with_retries
+{
+    source=$1
+    destination=$2
+
+    wget --tries=10 --quiet --output-document=${destination_file} ${url}
+}
+
 function download_file
 {
+    ###
+    # This will download a file whether by using cURL (first) or wget (second)
+    # if a destination file path is provided, it will be downloaded to that path.
+    # if not, the file will be downloaded to a tmp path and the path will be
+    # echoed so that it can be used as a return value.
+    # If the destination file already exists, it will be echoed back without being downloaded.
+    ###
     url=$1
-    destination_path=$2
+    destination_file=$2
 
     set +e
     curl_cmd=$(which curl)
     wget_cmd=$(which wget)
     set -e
 
-    if [[ -z ${destination_path} ]]; then
-        ctx logger info "Downloading ${url}..."
-        destination_path="/tmp/${RANDOM}.file"
-    else
-        ctx logger info "Downloading ${url} to ${destination_path}..."
+    if [[ -z ${destination_file} ]]; then
+        destination_file="/tmp/${RANDOM}.file"
     fi
-    if [[ ! -z ${curl_cmd} ]]; then
-        curl --fail --silent --location ${url} --create-dirs -o ${destination_path} >/dev/null
-    elif [[ ! -z ${wget_cmd} ]]; then
-        wget -O ${destination_path} ${url} >/dev/null
-    else
-        sys_error "Failed to download ${url}: Neither 'cURL' nor 'wget' were found on the system"
-    fi
-    echo ${destination_path}
-}
 
-function check_empty_var
-{
-    var=$1
-    message=$2
-
-    if [[ -z "${var}" ]]; then
-        sys_error "${message}"
-    fi
+    if [[ ! -e ${destination_file } ]]; then
+        if [[ ! -z ${curl_cmd} ]]; then
+            ctx logger info "Downloading ${url} to ${destination_file}..."
+            curl_download_with_retries ${url} ${destination_file}
+        elif [[ ! -z ${wget_cmd} ]]; then
+            ctx logger info "Downloading ${url} to ${destination_file}..."
+            # should create dir struct here as wget doesn't do it for us
+            wget_download_with_retries ${url} ${destination_file}
+        else
+            sys_error "Cannot download ${url}. Neither 'cURL' nor 'wget' were found on the system"
+        fi
+        echo ${destination_file}
+    else
+        ctx logger info "File ${destination_file} already exists..."
+        echo ${destination_file}
 }
 
 function copy_notice
 {
+    ###
+    # This is a generic implementation for copying NOTICE files for different
+    # services to /opt.
+    ###
     service=$1
 
     destination_notice="/opt/${service}_NOTICE.txt"
@@ -119,13 +145,21 @@ function copy_notice
 
 function wait_for_port
 {
-    c=0
+    ###
+    # services sometime take time to load. This allows us to wait for their
+    # port to open before we continue with other operations.
+    # for instance, before we create Elasticsearch mapping, we run Elasticsearch
+    # and wait for its port to be opened.
+    ###
+    port=$1
+
+    counter=0
     while ! echo exit | curl http://localhost:$1;
     do
             if [[ $c -gt 24 ]]; then
-                sys_error "Failed to connect to service... (status $?)"
+                sys_error "Failed to connect to port ${port}... (status $?)"
             fi
-            ctx logger info "Port $1 not available yet, retrying... ($c/24)"
+            ctx logger info "Port ${port} not available yet, retrying... ($counter/24)"
             sleep 5;
             c=$((c+1))
     done
@@ -133,6 +167,14 @@ function wait_for_port
 
 function yum_install
 {
+    ###
+    # yum supports installing from URL, path and the default yum repo
+    # configured within your image
+    # you can specify one of the following:
+    # [yum install -y] http://www.myrpmrepo.com/file.rpm
+    # [yum install -y] mylocalfile.rpm
+    # [yum install -y] mypackagename
+    ###
     source=$1
 
     ctx logger info "yum Installing ${source}..."
